# Generated by Django 6.0.7 on 2026-07-26 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='persona',
            name='imagen',
        ),
        migrations.AddField(
            model_name='persona',
            name='casa',
            field=models.CharField(choices=[('leon', 'León'), ('halcon', 'Halcón'), ('serpiente', 'Serpiente')], default='leon', max_length=20),
        ),
    ]
